import random

# Comprehensive list of items grouped by category, expanded into a flat list
items = [
"C Battery",
"C-Clamp",
"C.P.U.",
"Cab",
"Cabana",
"Cabaret",
"Caber",
"Cabin",
"Cabin Car",
"Cabin Class",
"Cabin Cruiser",
"Cabin Liner",
"Cabinet",
"Cabinetwork",
"Cable",
"Cable Car",
"Cable System",
"Cable Television",
"Cable Television Service",
"Caboose",
"Cabriolet",
"Cache",
"Cachet",
"Caddy",
"Caesium Clock",
"Cafe",
"Cafeteria",
"Cafeteria Facility",
"Cafeteria Tray",
"Caff",
"Caftan",
"Cage",
"Cagoule",
"Caisson",
"Cake",
"Calabash",
"Calabash Pipe",
"Calash",
"Calash Top",
"Calceus",
"Calcimine",
"Calculating Machine",
"Calculator",
"Caldron",
"Caleche",
"Calender",
"Calico",
"Caliper",
"Calk",
"Calkin",
"Call",
"Call Center",
"Call Centre",
"Call Forwarding",
"Call Waiting",
"Call-Back",
"Call-Board",
"Call-In",
"Caller Id",
"Calliope",
"Calliper",
"Calorimeter",
"Calpac",
"Calpack",
"Calumet",
"Calvary Cross",
"Cam",
"Camail",
"Camber Arch",
"Cambric",
"Camcorder",
"Camel'S Hair",
"Camelhair",
"Cameo",
"Camera",
"Camera Lens",
"Camera Lucida",
"Camera Obscura",
"Camera Tripod",
"Camise",
"Camisole",
"Camlet",
"Camo",
"Camouflage",
"Camp",
"Camp Bed",
"Camp Chair",
"Campaign Hat",
"Campanile",
"Camper",
"Camper Trailer",
"Camping Bus",
"Campstool",
"Camshaft",
"Can",
"Can Opener",
"Canal",
"Canal Boat",
"Candelabra",
"Candelabrum",
"Candid Camera",
"Candle",
"Candle Holder",
"Candlepin",
"Candlesnuffer",
"Candlestick",
"Candlewick",
"Candy Store",
"Candy Thermometer",
"Cane",
"Cangue",
"Canister",
"Canister Shot",
"Cannery",
"Cannikin",
"Cannister",
"Cannon",
"Cannon Ball",
"Cannonball",
"Cannula",
"Canoe",
"Canopic Jar",
"Canopic Vase",
"Canopy",
"Cant Hook",
"Canteen",
"Cantilever",
"Cantilever Bridge",
"Cantle",
"Canton Crepe",
"Canton Flannel",
"Cantonment",
"Canvas",
"Canvas Tent",
"Canvass",
"Cap",
"Cap Opener",
"Cap Screw",
"Capacitance",
"Capacitor",
"Capacitor Microphone",
"Caparison",
"Cape",
"Capeline Bandage",
"Capillary",
"Capillary Tube",
"Capillary Tubing",
"Capital Ship",
"Capitol",
"Capote",
"Capstan",
"Capstone",
"Capsule",
"Captain'S Chair",
"Capuchin",
"Car",
"Car Battery",
"Car Bomb",
"Car Carrier",
"Car Door",
"Car Mirror",
"Car Port",
"Car Seat",
"Car Tire",
"Car Train",
"Car Wheel",
"Car Window",
"Car-Ferry",
"Carabiner",
"Carack",
"Carafe",
"Caravan Inn",
"Caravansary",
"Caravanserai",
"Carbine",
"Carbon",
"Carbon Arc",
"Carbon Arc Lamp",
"Carbon Copy",
"Carboy",
"Carburetor",
"Carburettor",
"Card",
"Card Catalog",
"Card Catalogue",
"Card Index",
"Card Table",
"Cardcase",
"Cardiac Monitor",
"Cardigan",
"Cardiograph",
"Cardioid Microphone",
"Cardroom",
"Cargo",
"Cargo Area",
"Cargo Container",
"Cargo Deck",
"Cargo Door",
"Cargo Hatch",
"Cargo Helicopter",
"Cargo Hold",
"Cargo Liner",
"Cargo Ship",
"Cargo Vessel",
"Carillon",
"Caroche",
"Carousel",
"Carpenter'S Hammer",
"Carpenter'S Kit",
"Carpenter'S Level",
"Carpenter'S Mallet",
"Carpenter'S Rule",
"Carpenter'S Square",
"Carpet Beater",
"Carpet Loom",
"Carpet Pad",
"Carpet Sweeper",
"Carpet Tack",
"Carpetbag",
"Carport",
"Carrack",
"Carrel",
"Carrell",
"Carriage",
"Carriage Bolt",
"Carriage House",
"Carriage Wrench",
"Carriageway",
"Carrick Bend",
"Carrick Bitt",
"Carrier",
"Carrousel",
"Carryall",
"Carrycot",
"Cart",
"Carton",
"Cartoon",
"Cartouch",
"Cartouche",
"Cartridge",
"Cartridge Belt",
"Cartridge Clip",
"Cartridge Ejector",
"Cartridge Extractor",
"Cartridge Fuse",
"Cartridge Holder",
"Cartridge Remover",
"Cartwheel",
"Carving",
"Carving Fork",
"Carving Knife",
"Caryatid",
"Cascade Liquefier",
"Cascade Transformer",
"Case",
"Case Knife",
"Case Shot",
"Casein",
"Casein Paint",
"Casement",
"Casement Window",
"Casern",
"Cash Bar",
"Cash Dispenser",
"Cash Machine",
"Cash Register",
"Cashbox",
"Cashmere",
"Casing",
"Casino",
"Casket",
"Casque",
"Casquet",
"Casquetel",
"Cassegrainian Telescope",
"Casserole",
"Cassette",
"Cassette Deck",
"Cassette Player",
"Cassette Recorder",
"Cassette Tape",
"Cassock",
"Cast",
"Caster",
"Casting",
"Castle",
"Castor",
"Cat",
"Cat Box",
"Cat Cracker",
"Cat Scanner",
"Cat'S-Paw",
"Cat-O'-Nine-Tails",
"Catacomb",
"Catafalque",
"Catalog",
"Catalogue",
"Catalytic Converter",
"Catalytic Cracker",
"Catamaran",
"Catapult",
"Catboat",
"Catch",
"Catchall",
"Catcher'S Mask",
"Catchment",
"Catechism",
"Caterpillar",
"Catgut",
"Cathedra",
"Cathedral",
"Catheter",
"Cathode",
"Cathode-Ray Tube",
"Catling",
"Catsup Bottle",
"Cattle Boat",
"Cattle Car",
"Cattle Grid",
"Cattle Guard",
"Cattle Pen",
"Cattle Trail",
"Cattleship",
"Catwalk",
"Cauldron",
"Causeway",
"Cauterant",
"Cautery",
"Cavalier Hat",
"Cavalry Sword",
"Cavetto",
"Cavity Wall",
"Cd",
"Cd Burner",
"Cd Drive",
"Cd Player",
"Cd-R",
"Cd-Rom",
"Cd-Rom Drive",
"Cd-Wo",
"Cedar Chest",
"Ceiling",
"Celesta",
"Celestial Globe",
"Cell",
"Cellar",
"Cellarage",
"Cellblock",
"Cello",
"Cellophane",
"Cellphone",
"Cellular Phone",
"Cellular Telephone",
"Cellulose Tape",
"Celtic Cross",
"Cement",
"Cement Mixer",
"Cenotaph",
"Censer",
"Center",
"Center Bit",
"Center Punch",
"Centerboard",
"Centerpiece",
"Centigrade Thermometer",
"Central Heating",
"Central Processing Unit",
"Central Processor",
"Centre",
"Centre Bit",
"Centreboard",
"Centrepiece",
"Centrifugal Pump",
"Centrifuge",
"Ceramic",
"Ceramic Ware",
"Cereal Bowl",
"Cereal Box",
"Cerecloth",
"Cervical Cap",
"Cesspit",
"Cesspool",
"Chadar",
"Chaddar",
"Chador",
"Chaff",
"Chafing Dish",
"Chafing Gear",
"Chain",
"Chain Armor",
"Chain Armour",
"Chain Letter",
"Chain Mail",
"Chain Printer",
"Chain Saw",
"Chain Stitch",
"Chain Store",
"Chain Tongs",
"Chain Wrench",
"Chainlink Fence",
"Chainsaw",
"Chair",
"Chair Lift",
"Chair Of State",
"Chairlift",
"Chaise",
"Chaise Longue",
"Chalet",
"Chalice",
"Chalk",
"Chalk Line",
"Chalk Pit",
"Chalkpit",
"Challis",
"Chamber",
"Chamberpot",
"Chambray",
"Chamfer Bit",
"Chamfer Plane",
"Chamfron",
"Chamois Cloth",
"Chancel",
"Chancellery",
"Chancery",
"Chandelier",
"Chandlery",
"Chanfron",
"Change",
"Channel",
"Chanter",
"Chantry",
"Chap",
"Chapel",
"Chapterhouse",
"Character Printer",
"Character-At-A-Time Printer",
"Charcoal",
"Charcoal Burner",
"Charcuterie",
"Charge",
"Charge-Exchange Accelerator",
"Charger",
"Chariot",
"Charnel",
"Charnel House",
"Chart",
"Charterhouse",
"Chase",
"Chassis",
"Chasuble",
"Chat Room",
"Chateau",
"Chatelaine",
"Chatroom",
"Check",
"Checker",
"Checker Board",
"Checkerboard",
"Checkout",
"Checkout Counter",
"Checkroom",
"Cheekpiece",
"Cheese Cutter",
"Cheese Press",
"Cheese Tray",
"Cheeseboard",
"Cheesecake",
"Cheesecloth",
"Chemical Bomb",
"Chemical Plant",
"Chemical Reactor",
"Chemical Weapon",
"Chemise",
"Chenille",
"Chenille Cord",
"Chequer",
"Chess Board",
"Chess Piece",
"Chessboard",
"Chessman",
"Chest",
"Chest Of Drawers",
"Chest Protector",
"Chesterfield",
"Cheval Glass",
"Cheval-De-Frise",
"Chevaux-De-Frise",
"Chevron",
"Chiaroscuro",
"Chicane",
"Chicken Coop",
"Chicken Run",
"Chicken Wire",
"Chicken Yard",
"Chiffon",
"Chiffonier",
"Child'S Room",
"Chime",
"Chimney",
"Chimney Breast",
"Chimney Corner",
"Chimneypot",
"Chimneystack",
"Chin Rest",
"Chin Strap",
"China",
"China Cabinet",
"China Closet",
"Chinaware",
"Chinchilla",
"Chinese Lantern",
"Chinese Puzzle",
"Chinning Bar",
"Chino",
"Chinoiserie",
"Chintz",
"Chip",
"Chipboard",
"Chisel",
"Chiton",
"Chlamys",
"Chloroacetophenone",
"Chlorobenzylidenemalononitrile",
"Chock",
"Choir",
"Choir Loft",
"Choke",
"Choke Coil",
"Choker",
"Chokey",
"Choking Coil",
"Choky",
"Choo-Choo",
"Chopine",
"Chopper",
"Chopping Block",
"Chopping Board",
"Chopstick",
"Chordophone",
"Choreography",
"Choropleth Map",
"Christmas Stocking",
"Christmas Tree",
"Chromatography Column",
"Chronograph",
"Chronometer",
"Chronoscope",
"Chuck",
"Chuck Wagon",
"Chuddar",
"Chukka",
"Chukka Boot",
"Chum",
"Church",
"Church Bell",
"Church Building",
"Church Hat",
"Church Key",
"Church Tower",
"Churidars",
"Churn",
"Chute",
"Cider Mill",
"Ciderpress",
"Cigar Band",
"Cigar Box",
"Cigar Cutter",
"Cigar Lighter",
"Cigarette Case",
"Cigarette Holder",
"Cigarette Lighter",
"Cinch",
"Cinder Block",
"Cinder Track",
"Cinema",
"Cinema Verite",
"Cinerarium",
"Cinquefoil",
"Circle",
"Circlet",
"Circuit",
"Circuit Board",
"Circuit Breaker",
"Circuit Card",
"Circuitry",
"Circular Plane",
"Circular Saw",
"Circus",
"Circus Tent",
"Cistern",
"Cither",
"Cithern",
"Citole",
"Cittern",
"City Hall",
"City University",
"Cityscape",
"Civic Center",
"Civies",
"Civilian Clothing",
"Civilian Dress",
"Civilian Garb",
"Civvies",
"Clack",
"Clack Valve",
"Clamp",
"Clamshell",
"Clapboard",
"Clapper",
"Clapper Valve",
"Clapperboard",
"Clarence",
"Clarinet",
"Clarion",
"Clark Cell",
"Clark Standard Cell",
"Clasp",
"Clasp Knife",
"Classic",
"Classroom",
"Clavichord",
"Clavier",
"Claw Hammer",
"Claw Hatchet",
"Clawhammer",
"Clay Pigeon",
"Clay Pipe",
"Claymore",
"Claymore Mine",
"Clean Bomb",
"Clean Room",
"Cleaners",
"Cleaning Device",
"Cleaning Equipment",
"Cleaning Implement",
"Cleaning Pad",
"Clearstory",
"Clearway",
"Cleat",
"Cleats",
"Cleaver",
"Clerestory",
"Clerical Collar",
"Clevis",
"Clews",
"Cliff Dwelling",
"Climber",
"Climbing Frame",
"Climbing Iron",
"Clinch",
"Clincher",
"Cling Film",
"Clingfilm",
"Clinic",
"Clinical Thermometer",
"Clinker",
"Clinker Block",
"Clinker Brick",
"Clinometer",
"Clip",
"Clip Art",
"Clip Joint",
"Clip Lead",
"Clip-On",
"Clipboard",
"Clipper",
"Clipper Ship",
"Cloak",
"Cloakroom",
"Cloche",
"Clock",
"Clock Dial",
"Clock Face",
"Clock Pendulum",
"Clock Radio",
"Clock Tower",
"Clockwork",
"Clog",
"Cloisonne",
"Cloister",
"Closed Circuit",
"Closed Loop",
"Closed-Circuit Television",
"Closed-Loop System",
"Closet",
"Closeup",
"Closeup Lens",
"Clostridium Perfringens",
"Cloth Cap",
"Cloth Covering",
"Clothes Basket",
"Clothes Closet",
"Clothes Drier",
"Clothes Dryer",
"Clothes Hamper",
"Clothes Hanger",
"Clothes Peg",
"Clothes Pin",
"Clothes Tree",
"Clothesbrush",
"Clotheshorse",
"Clothesline",
"Clothespin",
"Clothespress",
"Clothing",
"Clothing Store",
"Cloud Chamber",
"Clout",
"Clout Nail",
"Clove Hitch",
"Club",
"Club Car",
"Clubhouse",
"Clubroom",
"Cluster Bomb",
"Clutch",
"Clutch Bag",
"Clutch Pedal",
"Cn Gas",
"Coach",
"Coach House",
"Coach-And-Four",
"Coal Car",
"Coal Chute",
"Coal House",
"Coal Mine",
"Coal Shovel",
"Coalbin",
"Coalface",
"Coalhole",
"Coalpit",
"Coaming",
"Coaster",
"Coaster Brake",
"Coat",
"Coat Button",
"Coat Closet",
"Coat Hanger",
"Coat Of Arms",
"Coat Of Paint",
"Coat Rack",
"Coat Stand",
"Coat Tree",
"Coatdress",
"Coatee",
"Coating",
"Coatrack",
"Coatroom",
"Coattail",
"Coax",
"Coax Cable",
"Coaxial Cable",
"Cobble",
"Cobblestone",
"Cobweb",
"Cockade",
"Cockcroft And Walton Accelerator",
"Cockcroft And Walton Voltage Multiplier",
"Cockcroft-Walton Accelerator",
"Cockcroft-Walton Voltage Multiplier",
"Cocked Hat",
"Cockhorse",
"Cockleshell",
"Cockloft",
"Cockpit",
"Cockscomb",
"Cocktail Dress",
"Cocktail Lounge",
"Cocktail Shaker",
"Cocktail Table",
"Cocotte",
"Codpiece",
"Coelostat",
"Coffee Bar",
"Coffee Can",
"Coffee Cup",
"Coffee Filter",
"Coffee Grinder",
"Coffee Maker",
"Coffee Mill",
"Coffee Mug",
"Coffee Shop",
"Coffee Stall",
"Coffee Table",
"Coffee Urn",
"Coffee-Table Book",
"Coffeehouse",
"Coffeepot",
"Coffer",
"Cofferdam",
"Coffey Still",
"Coffin",
"Cog",
"Coif",
"Coil",
"Coil Spring",
"Coin Box",
"Coin Slot",
"Colander",
"Cold Cathode",
"Cold Chisel",
"Cold Cream",
"Cold Frame",
"Cold-Water Flat",
"Coldcream",
"Collage",
"Collage Film",
"Collar",
"Collect Call",
"Collection",
"Collector",
"College",
"Collet",
"Collet Chuck",
"Collider",
"Collimator",
"Cologne",
"Cologne Water",
"Colonnade",
"Colonoscope",
"Colophon",
"Color Television",
"Color Television System",
"Color Television Tube",
"Color Tube",
"Color Tv",
"Color Tv Tube",
"Color Wash",
"Colorimeter",
"Coloring Book",
"Colors",
"Colour Supplement",
"Colour Television",
"Colour Television System",
"Colour Television Tube",
"Colour Tube",
"Colour Tv",
"Colour Tv Tube",
"Colour Wash",
"Colours",
"Colt",
"Colter",
"Columbarium",
"Column",
"Comb",
"Comber",
"Combination Lock",
"Combination Plane",
"Combine",
"Comforter",
"Comic Book",
"Coming Attraction",
"Command Key",
"Command Module",
"Command Post",
"Commercial Art",
"Commissary",
"Commode",
"Commodity",
"Common Ax",
"Common Axe",
"Common Room",
"Commonplace Book",
"Communication Equipment",
"Communication System",
"Communications Satellite",
"Community Center",
"Commutator",
"Commuter",
"Commuter Train",
"Compact",
"Compact Car",
"Compact Disc",
"Compact Disc Read-Only Memory",
"Compact Disc Recordable",
"Compact Disc Write-Once",
"Compact Disk",
"Compact-Disk Burner",
"Companionway",
"Compartment",
"Compass",
"Compass Card",
"Compass Plane",
"Compass Saw",
"Compendium",
"Compilation",
"Composition",
"Compositor'S Case",
"Compound",
"Compound Lens",
"Compound Lever",
"Compound Microscope",
"Compress",
"Compression Bandage",
"Compressor",
"Computer",
"Computer Circuit",
"Computer Display",
"Computer Graphics",
"Computer Keyboard",
"Computer Monitor",
"Computer Network",
"Computer Screen",
"Computer Store",
"Computer System",
"Computerized Axial Tomography Scanner",
"Computing Device",
"Computing Machine",
"Computing System",
"Concentration Camp",
"Concept Album",
"Concert Grand",
"Concert Hall",
"Concert Piano",
"Concertina",
"Concourse",
"Concrete",
"Concrete Mixer",
"Condensation Pump",
"Condenser",
"Condenser Microphone",
"Condo",
"Condom",
"Condominium",
"Conductor",
"Conduit",
"Cone",
"Cone Clutch",
"Cone Friction Clutch",
"Conestoga",
"Conestoga Wagon",
"Confectionary",
"Confectionery",
"Conference Call",
"Conference Center",
"Conference House",
"Conference Room",
"Conference Table",
"Confessional",
"Conformal Projection",
"Conformation",
"Conge",
"Congee",
"Congress Boot",
"Congress Gaiter",
"Congress Shoe",
"Conic Projection",
"Conical Projection",
"Connecter",
"Connecting Rod",
"Connecting Room",
"Connection",
"Connective",
"Connector",
"Connexion",
"Conning Tower",
"Conservatoire",
"Conservatory",
"Consignment",
"Console",
"Console Table",
"Consuetudinal",
"Consuetudinary",
"Consulate",
"Consumer Goods",
"Contact",
"Contact Lens",
"Contact Print",
"Container",
"Container Ship",
"Container Vessel",
"Containership",
"Containment",
"Contour Map",
"Contraband",
"Contrabassoon",
"Contraceptive",
"Contraceptive Device",
"Contrafagotto",
"Control",
"Control Board",
"Control Center",
"Control Circuit",
"Control Key",
"Control Panel",
"Control Rod",
"Control Room",
"Control System",
"Control Tower",
"Controller",
"Convector",
"Convenience Store",
"Convent",
"Conventicle",
"Converging Lens",
"Converter",
"Convertible",
"Convertor",
"Convex Lens",
"Conveyance",
"Cookbook",
"Cooker",
"Cookery Book",
"Cookfire",
"Cookhouse",
"Cookie Cutter",
"Cookie Jar",
"Cookie Sheet",
"Cooking Utensil",
"Cookstove",
"Cookware",
"Cooky Jar",
"Coolant System",
"Cooler",
"Cooling",
"Cooling System",
"Cooling Tower",
"Coonskin",
"Coonskin Cap",
"Coop",
"Cope",
"Copestone",
"Coping Saw",
"Coping Stone",
"Copper Mine",
"Copperplate",
"Copperplate Engraving",
"Copperware",
"Copy",
"Copybook",
"Copyholder",
"Coquille",
"Coracle",
"Corbel",
"Corbel Arch",
"Corbel Step",
"Corbie Gable",
"Corbie-Step",
"Corbiestep",
"Cord",
"Cordage",
"Cordon",
"Cords",
"Corduroy",
"Corduroys",
"Core",
"Core Bit",
"Core Drill",
"Corer",
"Cork",
"Corkboard",
"Corker",
"Corkscrew",
"Corncrib",
"Corner",
"Corner Post",
"Cornerstone",
"Cornet",
"Cornice",
"Coronet",
"Corral",
"Correctional Institution",
"Corrective",
"Corridor",
"Corrugated Fastener",
"Corrugated Iron",
"Corsair",
"Corselet",
"Corset",
"Corslet",
"Corvette",
"Cosmetic",
"Cosmography",
"Cosmotron",
"Costume",
"Cosy",
"Cot",
"Cote",
"Cottage Tent",
"Cottar",
"Cotter",
"Cotter Pin",
"Cotton",
"Cotton Flannel",
"Cotton Gin",
"Cotton Mill",
"Couch",
"Couchette",
"Coude System",
"Coude Telescope",
"Coulisse",
"Coulter",
"Council Board",
"Council Table",
"Counter",
"Counter Tube",
"Counterbalance",
"Counterbore",
"Counterfeit",
"Counterpart",
"Counterpoise",
"Countersink",
"Countersink Bit",
"Countertop",
"Counterweight",
"Countinghouse",
"Country House",
"Country Store",
"Coupe",
"Coupler",
"Coupling",
"Course",
"Course Catalog",
"Course Catalogue",
"Court",
"Court Plaster",
"Courtelle",
"Courthouse",
"Courtroom",
"Courtyard",
"Cover",
"Cover Glass",
"Cover Letter",
"Cover Plate",
"Cover Slip",
"Cover Song",
"Cover Version",
"Coverall",
"Covered Bridge",
"Covered Couch",
"Covered Wagon",
"Covering",
"Covering Letter",
"Covering Material",
"Coverlet",
"Cow Barn",
"Cow Pen",
"Cowbarn",
"Cowbell",
"Cowboy Boot",
"Cowboy Hat",
"Cowhide",
"Cowhouse",
"Cowl",
"Cowshed",
"Coxcomb",
"Cozy",
"Cpu",
"Cpu Board",
"Crackle",
"Crackle China",
"Crackleware",
"Cradle",
"Craft",
"Crammer",
"Cramp",
"Cramp Iron",
"Crampon",
"Crampoon",
"Crane",
"Craniometer",
"Crank",
"Crank Call",
"Crank Handle",
"Crank Letter",
"Crankcase",
"Crankshaft",
"Crape",
"Crash Barrier",
"Crash Helmet",
"Crate",
"Cravat",
"Crayon",
"Crazy Quilt",
"Cream",
"Cream Pitcher",
"Creamer",
"Creation",
"Creche",
"Credence",
"Credenza",
"Creel",
"Creep",
"Cremation Chamber",
"Crematorium",
"Crematory",
"Crepe",
"Crepe De Chine",
"Crescent Wrench",
"Crest",
"Cretonne",
"Crew Neck",
"Crew Neckline",
"Crewelwork",
"Crewet",
"Crib",
"Cribbage Board",
"Cricket Ball",
"Cricket Bat",
"Cricket Equipment",
"Crimper",
"Cringle",
"Crinoline",
"Crisscross",
"Crochet",
"Crochet Hook",
"Crochet Needle",
"Crochet Stitch",
"Crocheting",
"Crock",
"Crock Pot",
"Crockery",
"Crocket",
"Crook",
"Crookes Radiometer",
"Crookes Tube",
"Crop",
"Croquet Ball",
"Croquet Equipment",
"Croquet Mallet",
"Cross",
"Cross Bit",
"Cross Of Calvary",
"Cross Street",
"Cross-Stitch",
"Crossbar",
"Crossbench",
"Crossbow",
"Crosscut Handsaw",
"Crosscut Saw",
"Crosse",
"Crosshead",
"Crossing",
"Crossjack",
"Crossover",
"Crosspiece",
"Crosswalk",
"Crossword",
"Crossword Puzzle",
"Crotchet",
"Croupier'S Rake",
"Crow Step",
"Crow'S Nest",
"Crowbar",
"Crown",
"Crown Jewel",
"Crown Jewels",
"Crown Lens",
"Crown Of Thorns",
"Crown Saw",
"Crownwork",
"Crt",
"Crucible",
"Crucifix",
"Cruet",
"Cruet-Stand",
"Cruise Control",
"Cruise Liner",
"Cruise Missile",
"Cruise Ship",
"Cruiser",
"Crupper",
"Cruse",
"Crusher",
"Crutch",
"Cryocautery",
"Cryometer",
"Cryoscope",
"Cryostat",
"Crypt",
"Cryptograph",
"Crystal",
"Crystal Counter",
"Crystal Detector",
"Crystal Microphone",
"Crystal Oscillator",
"Crystal Pickup",
"Crystal Set",
"Cs Gas",
"Cubby",
"Cubbyhole",
"Cube",
"Cubicle",
"Cubitiere",
"Cucking Stool",
"Cuckoo Clock",
"Cuddy",
"Cudgel",
"Cue",
"Cue Ball",
"Cue Stick",
"Cuff",
"Cufflink",
"Cuirass",
"Cuisse",
"Cul",
"Cul De Sac",
"Culdoscope",
"Cullender",
"Cullis",
"Culotte",
"Cultivator",
"Culverin",
"Culvert",
"Cummerbund",
"Cup",
"Cup Hook",
"Cupboard",
"Cupid'S Bow",
"Cupola",
"Curb",
"Curb Bit",
"Curb Roof",
"Curbing",
"Curbside",
"Curbstone",
"Curet",
"Curette",
"Curiosa",
"Curler",
"Curling Iron",
"Currycomb",
"Cursor",
"Curtain",
"Curtain Ring",
"Cushion",
"Cuspidation",
"Customhouse",
"Customshouse",
"Cut",
"Cut Glass",
"Cutaway",
"Cutaway Drawing",
"Cutaway Model",
"Cutlas",
"Cutlass",
"Cutlery",
"Cutoff",
"Cutoff Saw",
"Cutout",
"Cutter",
"Cutting Board",
"Cutting Implement",
"Cutting Room",
"Cutting Tool",
"Cutty Stool",
"Cutwork",
"Cyberart",
"Cybercafe",
"Cyclopean Masonry",
"Cyclostyle",
"Cyclotron",
"Cylinder",
"Cylinder Head",
"Cylinder Lock",
"Cyma",
"Cyma Recta",
"Cymatium",
"Cymbal",
"Cytophotometer",
  "B Battery",
"B-Flat Clarinet",
"Babushka",
"Baby Bed",
"Baby Buggy",
"Baby Carriage",
"Baby Grand",
"Baby Grand Piano",
"Baby Powder",
"Baby Shoe",
"Baby'S Bed",
"Bacillus Anthracis",
"Back",
"Back Brace",
"Back Door",
"Back Entrance",
"Back Pack",
"Back Porch",
"Back Room",
"Back Saw",
"Backband",
"Backbench",
"Backboard",
"Backbone",
"Backcloth",
"Backdoor",
"Backdrop",
"Backgammon Board",
"Background",
"Backhoe",
"Backing",
"Backlighting",
"Backpack",
"Backpacking Tent",
"Backplate",
"Backrest",
"Backroom",
"Backsaw",
"Backscratcher",
"Backseat",
"Backspace",
"Backspace Key",
"Backspacer",
"Backstairs",
"Backstay",
"Backstitch",
"Backstop",
"Backsword",
"Backup",
"Backup System",
"Bacteria Bed",
"Badminton Equipment",
"Badminton Racket",
"Badminton Racquet",
"Baedeker",
"Baffle",
"Baffle Board",
"Bag",
"Baggage",
"Baggage Car",
"Baggage Claim",
"Bagger",
"Bagnio",
"Bagpipe",
"Bailey",
"Bailey Bridge",
"Bain-Marie",
"Bait",
"Baize",
"Bakehouse",
"Bakery",
"Bakeshop",
"Balaclava",
"Balaclava Helmet",
"Balalaika",
"Balance",
"Balance Beam",
"Balance Wheel",
"Balbriggan",
"Balcony",
"Baldachin",
"Baldric",
"Baldrick",
"Bale",
"Baling Wire",
"Ball",
"Ball And Chain",
"Ball Bearing",
"Ball Cartridge",
"Ball Cock",
"Ball Gown",
"Ball Valve",
"Ball-And-Socket Joint",
"Ball-Peen Hammer",
"Ballast",
"Ballast Resistor",
"Ballcock",
"Balldress",
"Ballet Skirt",
"Ballistic Galvanometer",
"Ballistic Missile",
"Ballistic Pendulum",
"Ballistocardiograph",
"Balloon",
"Balloon Bomb",
"Balloon Sail",
"Balloon Seat",
"Ballot Box",
"Ballpark",
"Ballpen",
"Ballpoint",
"Ballpoint Pen",
"Ballroom",
"Balmoral",
"Balsa Raft",
"Baluster",
"Balusters",
"Balustrade",
"Banana Boat",
"Band",
"Band Aid",
"Band Saw",
"Bandage",
"Bandana",
"Bandanna",
"Bandbox",
"Bandeau",
"Banderilla",
"Banding",
"Bandoleer",
"Bandolier",
"Bandoneon",
"Bandsaw",
"Bandstand",
"Bandwagon",
"Bangalore Torpedo",
"Bangle",
"Banian",
"Banister",
"Banjo",
"Bank",
"Bank Building",
"Banner",
"Bannister",
"Banquette",
"Banyan",
"Baptismal Font",
"Baptistery",
"Baptistry",
"Bar",
"Bar Bit",
"Bar Magnet",
"Bar Mask",
"Bar Printer",
"Bar Sinister",
"Barbacan",
"Barbecue",
"Barbed Wire",
"Barbell",
"Barbeque",
"Barber Chair",
"Barbershop",
"Barbette",
"Barbette Carriage",
"Barbican",
"Barbwire",
"Bard",
"Bareboat",
"Barge",
"Barge Pole",
"Bargello",
"Baritone",
"Baritone Horn",
"Bark",
"Barn",
"Barn Door",
"Barndoor",
"Barnyard",
"Barograph",
"Barometer",
"Barong",
"Barouche",
"Barque",
"Barrack",
"Barrage Balloon",
"Barrel",
"Barrel Knot",
"Barrel Organ",
"Barrel Vault",
"Barrelhouse",
"Barrette",
"Barretter",
"Barricade",
"Barrier",
"Barroom",
"Barrow",
"Bas Relief",
"Bascule",
"Base",
"Base Of Operations",
"Baseball",
"Baseball Bat",
"Baseball Cap",
"Baseball Equipment",
"Baseball Glove",
"Baseball Mitt",
"Baseboard",
"Basement",
"Basic",
"Basic Point Defense Missile System",
"Basilica",
"Basilisk",
"Basin",
"Basinet",
"Basket",
"Basket Weave",
"Basketball",
"Basketball Backboard",
"Basketball Equipment",
"Basketball Hoop",
"Bass",
"Bass Clarinet",
"Bass Drum",
"Bass Fiddle",
"Bass Guitar",
"Bass Horn",
"Bass Viol",
"Basset Horn",
"Bassinet",
"Basso Relievo",
"Basso Rilievo",
"Bassoon",
"Bastard",
"Baste",
"Baster",
"Bastille",
"Bastinado",
"Basting",
"Basting Stitch",
"Bastion",
"Bat",
"Bath",
"Bath Chair",
"Bath Linen",
"Bath Mat",
"Bath Oil",
"Bath Salts",
"Bath Towel",
"Bathhouse",
"Bathing Cap",
"Bathing Machine",
"Bathing Tub",
"Bathometer",
"Bathrobe",
"Bathroom",
"Bathroom Fixture",
"Bathtub",
"Bathymeter",
"Bathyscape",
"Bathyscaph",
"Bathyscaphe",
"Bathysphere",
"Batik",
"Batiste",
"Baton",
"Batten",
"Batter'S Box",
"Battering Ram",
"Battery",
"Batting",
"Batting Cage",
"Batting Glove",
"Batting Helmet",
"Battle Cruiser",
"Battle Dress",
"Battle Flag",
"Battle Sight",
"Battle-Ax",
"Battle-Axe",
"Battledore",
"Battlement",
"Battleship",
"Battlesight",
"Battlewagon",
"Batwing",
"Bauble",
"Bay",
"Bay Rum",
"Bay Window",
"Bayonet",
"Bazaar",
"Bazar",
"Bazooka",
"Bb",
"Bb Gun",
"Bb Shot",
"Bbs",
"Beach Ball",
"Beach House",
"Beach Towel",
"Beach Waggon",
"Beach Wagon",
"Beachball",
"Beachwear",
"Beacon",
"Beacon Light",
"Bead",
"Beading",
"Beading Plane",
"Beadwork",
"Beaker",
"Beam",
"Beam Balance",
"Beanbag",
"Beanie",
"Beany",
"Bear Claw",
"Bearing",
"Bearing Rein",
"Bearing Wall",
"Bearskin",
"Beater",
"Beating-Reed Instrument",
"Beauty Spot",
"Beaver",
"Beaver Board",
"Becket",
"Beckman Thermometer",
"Bed",
"Bed And Breakfast",
"Bed Clothing",
"Bed Cover",
"Bed Covering",
"Bed Jacket",
"Bed Linen",
"Bed Pillow",
"Bed-And-Breakfast",
"Bedchamber",
"Bedclothes",
"Bedcover",
"Bedding",
"Bedford Cord",
"Bedframe",
"Bedlam",
"Bedpan",
"Bedpost",
"Bedroll",
"Bedroom",
"Bedroom Furniture",
"Bedsit",
"Bedsitter",
"Bedsitting Room",
"Bedspread",
"Bedspring",
"Bedstead",
"Beefcake",
"Beehive",
"Beeper",
"Beer Barrel",
"Beer Bottle",
"Beer Can",
"Beer Garden",
"Beer Glass",
"Beer Hall",
"Beer Keg",
"Beer Mat",
"Beer Mug",
"Belaying Pin",
"Belfry",
"Bell",
"Bell Arch",
"Bell Cot",
"Bell Cote",
"Bell Deck",
"Bell Foundry",
"Bell Gable",
"Bell Glass",
"Bell Jar",
"Bell Push",
"Bell Seat",
"Bell Tent",
"Bell Tower",
"Bell-Bottoms",
"Bellarmine",
"Bellbottom Pants",
"Bellbottom Trousers",
"Bellows",
"Bellpull",
"Bellyband",
"Belt",
"Belt Ammunition",
"Belt Buckle",
"Belted Ammunition",
"Belting",
"Beltway",
"Belvedere",
"Bench",
"Bench Clamp",
"Bench Hook",
"Bench Lathe",
"Bench Press",
"Bend",
"Bend Dexter",
"Bend Sinister",
"Bender",
"Beret",
"Berlin",
"Bermuda Shorts",
"Berretta",
"Berth",
"Besom",
"Bessemer Converter",
"Best Seller",
"Bestiary",
"Bestseller",
"Betatron",
"Bethel",
"Betting Shop",
"Bevatron",
"Bevel",
"Bevel Gear",
"Bevel Square",
"Bezel",
"Bi-Fold Door",
"Bib",
"Bib-And-Tucker",
"Bible",
"Bicorn",
"Bicorne",
"Bicycle",
"Bicycle Chain",
"Bicycle Clip",
"Bicycle Pump",
"Bicycle Rack",
"Bicycle Seat",
"Bicycle Wheel",
"Bicycle-Built-For-Two",
"Bidding",
"Bidet",
"Bier",
"Bifocals",
"Big Blue",
"Big Board",
"Biggin",
"Bijou",
"Bike",
"Bikini",
"Bikini Pants",
"Bilge Keel",
"Bilge Pump",
"Bilge Well",
"Bilingual Dictionary",
"Bill",
"Billboard",
"Billet",
"Billhook",
"Billiard Ball",
"Billiard Hall",
"Billiard Marker",
"Billiard Parlor",
"Billiard Parlour",
"Billiard Room",
"Billiard Saloon",
"Bimetallic Strip",
"Bimonthly",
"Bin",
"Bin Liner",
"Binder",
"Binding",
"Binnacle",
"Binocular Microscope",
"Binoculars",
"Bioarm",
"Biochip",
"Biohazard Suit",
"Biological Weapon",
"Bioscope",
"Bioweapon",
"Biplane",
"Biprism",
"Birch",
"Birch Bark",
"Birch Rod",
"Birchbark",
"Birchbark Canoe",
"Bird Feeder",
"Bird Shot",
"Birdbath",
"Birdcage",
"Birdcage Mask",
"Birdcall",
"Birdfeeder",
"Birdhouse",
"Biretta",
"Biro",
"Birretta",
"Bishop",
"Bistro",
"Bit",
"Bite Plate",
"Biteplate",
"Bitewing",
"Bitmap",
"Bitt",
"Bitt Pin",
"Bitumastic",
"Biweekly",
"Black",
"Black And White",
"Black Box",
"Black Flag",
"Black Tie",
"Blackboard",
"Blackboard Eraser",
"Blackface",
"Blackjack",
"Blacktop",
"Blacktopping",
"Blackwall Hitch",
"Blackwash",
"Bladder",
"Blade",
"Blank",
"Blank Shell",
"Blanket",
"Blanket Stitch",
"Blast Furnace",
"Blasting Cap",
"Blaze",
"Blazer",
"Blender",
"Blimp",
"Blind",
"Blind Alley",
"Blindfold",
"Bling",
"Bling Bling",
"Blinker",
"Blister Pack",
"Block",
"Block And Tackle",
"Block Diagram",
"Block Plane",
"Blockade",
"Blockade-Runner",
"Blockage",
"Blockbuster",
"Blockhouse",
"Blood Knot",
"Bloodmobile",
"Bloomers",
"Blouse",
"Blow Tube",
"Blower",
"Blowgun",
"Blowlamp",
"Blowpipe",
"Blowtorch",
"Blowtube",
"Blu-82",
"Blucher",
"Bludgeon",
"Blue",
"Blue Book",
"Blue Chip",
"Bluebonnet",
"Blueprint",
"Blunderbuss",
"Blunt File",
"Board",
"Board Rule",
"Boarding",
"Boarding House",
"Boardinghouse",
"Boardroom",
"Boards",
"Boardwalk",
"Boat",
"Boat Deck",
"Boat Hook",
"Boat Train",
"Boat Whistle",
"Boater",
"Boathouse",
"Boatswain'S Chair",
"Bob",
"Bobber",
"Bobbin",
"Bobby Pin",
"Bobfloat",
"Bobsled",
"Bobsleigh",
"Bocce Ball",
"Bocci Ball",
"Boccie Ball",
"Bodega",
"Bodice",
"Bodkin",
"Body",
"Body Armor",
"Body Armour",
"Body Bag",
"Body Lotion",
"Body Pad",
"Body Plethysmograph",
"Body Stocking",
"Bodywork",
"Bofors Gun",
"Bogey",
"Bogie",
"Bogy",
"Boiler",
"Boilerplate",
"Boiling Water Reactor",
"Bola",
"Bola Tie",
"Bolero",
"Bollard",
"Bollock",
"Bolo",
"Bolo Knife",
"Bolo Tie",
"Bolometer",
"Bolster",
"Bolt",
"Bolt Cutter",
"Bomb",
"Bomb Calorimeter",
"Bomb Rack",
"Bomb Shelter",
"Bombard",
"Bombardon",
"Bombazine",
"Bomber",
"Bomber Jacket",
"Bombie",
"Bomblet",
"Bombproof",
"Bombshell",
"Bombsight",
"Bone China",
"Bone-Ash Cup",
"Bones",
"Boneshaker",
"Bongo",
"Bongo Drum",
"Bonnet",
"Booby Hatch",
"Book",
"Book Bag",
"Book Binding",
"Book Jacket",
"Book Of Knowledge",
"Bookcase",
"Bookend",
"Booklet",
"Bookmark",
"Bookmarker",
"Bookmobile",
"Bookshelf",
"Bookshop",
"Bookstall",
"Bookstore",
"Boom",
"Boomerang",
"Booster",
"Booster Amplifier",
"Booster Rocket",
"Booster Station",
"Booster Unit",
"Boot",
"Boot Camp",
"Bootee",
"Booth",
"Boothose",
"Bootie",
"Bootjack",
"Bootlace",
"Bootleg",
"Bootstrap",
"Bore",
"Bore Bit",
"Bore-Hole",
"Borer",
"Boron Chamber",
"Boron Counter Tube",
"Borstal",
"Bosom",
"Boston Rocker",
"Bosun'S Chair",
"Bota",
"Bottle",
"Bottle Bank",
"Bottle Opener",
"Bottlebrush",
"Bottlecap",
"Bottling Plant",
"Bottom",
"Botulin",
"Botulinus Toxin",
"Botulismotoxin",
"Boucle",
"Boudoir",
"Boule",
"Boulle",
"Bouncing Betty",
"Bouquet",
"Boutique",
"Boutonniere",
"Bow",
"Bow And Arrow",
"Bow Tie",
"Bow Window",
"Bow-Tie",
"Bowed Stringed Instrument",
"Bowie Knife",
"Bowknot",
"Bowl",
"Bowler",
"Bowler Hat",
"Bowline",
"Bowline Knot",
"Bowling Alley",
"Bowling Ball",
"Bowling Equipment",
"Bowling Pin",
"Bowling Shoe",
"Bowsprit",
"Bowstring",
"Bowtie",
"Box",
"Box Beam",
"Box Camera",
"Box Coat",
"Box End Wrench",
"Box Girder",
"Box Kite",
"Box Kodak",
"Box Office",
"Box Seat",
"Box Spring",
"Box Wrench",
"Boxcar",
"Boxing Equipment",
"Boxing Glove",
"Boxing Ring",
"Bra",
"Brace",
"Brace And Bit",
"Brace Wrench",
"Bracelet",
"Bracer",
"Braces",
"Bracing",
"Bracket",
"Brad",
"Bradawl",
"Braid",
"Braiding",
"Brail",
"Brake",
"Brake Band",
"Brake Cylinder",
"Brake Disk",
"Brake Lining",
"Brake Pad",
"Brake Pedal",
"Brake Shoe",
"Brake System",
"Brakes",
"Branch Line",
"Brasier",
"Brass",
"Brass Instrument",
"Brass Knuckles",
"Brass Knucks",
"Brass Monkey",
"Brassard",
"Brasserie",
"Brassie",
"Brassiere",
"Brattice",
"Brazier",
"Bread Board",
"Bread Knife",
"Bread-Bin",
"Breadbasket",
"Breadboard",
"Breadbox",
"Break Seal",
"Breakable",
"Breakfast Area",
"Breakfast Nook",
"Breakfast Table",
"Breakwater",
"Breast Drill",
"Breast Implant",
"Breast Pocket",
"Breastpin",
"Breastplate",
"Breathalyser",
"Breathalyzer",
"Breathing Apparatus",
"Breathing Device",
"Breathing Machine",
"Breech",
"Breech Closer",
"Breechblock",
"Breechcloth",
"Breechclout",
"Breeches",
"Breeches Buoy",
"Breechloader",
"Breeder Reactor",
"Bren",
"Bren Gun",
"Breviary",
"Brewery",
"Brewpub",
"Briar",
"Briar Pipe",
"Brick",
"Brick Trowel",
"Brickkiln",
"Bricklayer'S Hammer",
"Bricks And Mortar",
"Brickwork",
"Bridal Gown",
"Bridge",
"Bridge Circuit",
"Bridge Deck",
"Bridged-T",
"Bridgework",
"Bridle",
"Bridle Path",
"Bridle Road",
"Bridoon",
"Briefcase",
"Briefcase Bomb",
"Briefcase Computer",
"Briefs",
"Brig",
"Brigandine",
"Brigantine",
"Brilliant Pebble",
"Brilliantine",
"Brim",
"Briquet",
"Briquette",
"Bristle Brush",
"Britches",
"Broach",
"Broad Arrow",
"Broad Gauge",
"Broad Hatchet",
"Broadax",
"Broadaxe",
"Broadcast Station",
"Broadcaster",
"Broadcasting",
"Broadcasting Station",
"Broadcloth",
"Broadloom",
"Broadside",
"Broadsword",
"Brocade",
"Brochette",
"Brochure",
"Brogan",
"Brogue",
"Broiler",
"Broken Arch",
"Bronchoscope",
"Bronze",
"Brooch",
"Broom",
"Broom Closet",
"Brougham",
"Browning Automatic Rifle",
"Browning Machine Gun",
"Brownstone",
"Brunch Coat",
"Brush",
"Brussels Carpet",
"Brussels Lace",
"Bubble",
"Bubble Chamber",
"Bubble Jet Printer",
"Bubble Pack",
"Bubble-Jet Printer",
"Bubblejet",
"Bubbler",
"Buckboard",
"Bucket",
"Bucket Seat",
"Bucket Shop",
"Buckle",
"Buckram",
"Bucksaw",
"Buckshot",
"Buckskins",
"Buff",
"Buffer",
"Buffer Storage",
"Buffer Store",
"Buffet",
"Buffing Wheel",
"Bug",
"Buggy",
"Buggy Whip",
"Bugle",
"Buhl",
"Building",
"Building Block",
"Building Complex",
"Building Material",
"Building Supply House",
"Building Supply Store",
"Built In Bed",
"Built-In Bed",
"Bulkhead",
"Bull Fiddle",
"Bull Tongue",
"Bulla",
"Bulldog Clip",
"Bulldog Wrench",
"Bulldozer",
"Bullet",
"Bullet Train",
"Bulletin Board",
"Bulletin Board System",
"Bulletproof Vest",
"Bullfight",
"Bullhorn",
"Bullion",
"Bullnose",
"Bullnosed Plane",
"Bullock Block",
"Bullpen",
"Bullring",
"Bulwark",
"Bumboat",
"Bumper",
"Bumper Car",
"Bumper Guard",
"Bumper Jack",
"Bundle",
"Bung",
"Bungalow",
"Bungee",
"Bungee Cord",
"Bunghole",
"Bunk",
"Bunk Bed",
"Bunker",
"Bunsen",
"Bunsen Burner",
"Bunting",
"Bur",
"Burberry",
"Buret",
"Burette",
"Burglar Alarm",
"Burial Chamber",
"Burial Garment",
"Burial Mound",
"Burin",
"Burka",
"Burlap",
"Burn Bag",
"Burn Center",
"Burner",
"Burnoose",
"Burnous",
"Burnouse",
"Burp Gun",
"Burqa",
"Burr",
"Burthen",
"Bus",
"Bus Depot",
"Bus Lane",
"Bus Station",
"Bus Terminal",
"Busbar",
"Busby",
"Bush Jacket",
"Bushel Basket",
"Bushing",
"Business Letter",
"Business Suit",
"Buskin",
"Bust",
"Bustier",
"Bustle",
"Butcher Block",
"Butcher Board",
"Butcher Knife",
"Butcher Shop",
"Butt",
"Butt Hinge",
"Butt Joint",
"Butt Shaft",
"Butt Weld",
"Butt-Weld",
"Butter Dish",
"Butter Knife",
"Butterfly Valve",
"Buttery",
"Button",
"Button Hole",
"Buttonhole",
"Buttonhole Stitch",
"Buttonhook",
"Buttress",
"Buttressing",
"Buzz Bomb",
"Buzzer",
"Bvd",
"Bvd'S",
"Bwr",
"By-Product",
"Bypass",
"Bypass Capacitor",
"Bypass Condenser",
"Bypath",
"Byproduct",
"Byroad",
"Byway",

      "A Battery",
"A-Bomb",
"A-Line",
"Aba",
"Abacus",
"Abandoned Ship",
"Abatis",
"Abattis",
"Abattoir",
"Abaya",
"Abbe Condenser",
"Abbey",
"Abm",
"Abney Level",
"Abradant",
"Abrader",
"Abrading Stone",
"Abstract Art",
"Abstraction",
"Abstractionism",
"Abutment",
"Abutment Arch",
"Academic Costume",
"Academic Gown",
"Academic Robe",
"Academy",
"Accelerator",
"Accelerator Pedal",
"Accelerometer",
"Access",
"Access Road",
"Accessory",
"Accommodating Iol",
"Accommodating Lens Implant",
"Accommodation",
"Accommodation Ladder",
"Accordion",
"Accouterment",
"Accoutrement",
"Accumulator",
"Accumulator Register",
"Acetate",
"Acetate Disk",
"Acetate Rayon",
"Achromatic Lens",
"Ack-Ack",
"Ack-Ack Gun",
"Acorn Tube",
"Acoustic Delay Line",
"Acoustic Device",
"Acoustic Guitar",
"Acoustic Modem",
"Acoustic Storage",
"Acropolis",
"Acrylic",
"Acrylic Paint",
"Actinometer",
"Action",
"Action Mechanism",
"Active Matrix Screen",
"Actuator",
"Adapter",
"Adaptor",
"Adder",
"Adding Machine",
"Addressing Machine",
"Addressograph",
"Adhesive Bandage",
"Adhesive Tape",
"Adit",
"Adjoining Room",
"Adjustable Spanner",
"Adjustable Wrench",
"Adobe",
"Adobe Brick",
"Adornment",
"Adumbration",
"Adz",
"Adze",
"Aeolian Harp",
"Aeolian Lyre",
"Aerator",
"Aerial",
"Aerial Ladder",
"Aerial Torpedo",
"Aerodrome",
"Aerofoil",
"Aerogram",
"Aerogramme",
"Aeroplane",
"Aerosol",
"Aerosol Bomb",
"Aerosol Can",
"Aerosol Container",
"Aertex",
"Afghan",
"Aflatoxin",
"Afro-Wig",
"After-Shave",
"After-Shave Lotion",
"Afterburner",
"Afterdeck",
"Afterpiece",
"Agal",
"Agateware",
"Agglomerator",
"Aglet",
"Agony Column",
"Agora",
"Aiglet",
"Aigret",
"Aigrette",
"Aiguilette",
"Aileron",
"Air Bag",
"Air Base",
"Air Cleaner",
"Air Compressor",
"Air Conditioner",
"Air Conditioning",
"Air Cushion",
"Air Duct",
"Air Filter",
"Air Gun",
"Air Hammer",
"Air Hole",
"Air Horn",
"Air Hose",
"Air Letter",
"Air Lock",
"Air Mattress",
"Air Passage",
"Air Pump",
"Air Rifle",
"Air Search Radar",
"Air Shaft",
"Air Spring",
"Air Station",
"Air Terminal",
"Air Transportation System",
"Air Well",
"Air-Intake",
"Air-To-Air Missile",
"Air-To-Ground Missile",
"Air-To-Surface Missile",
"Airbrake",
"Airbrush",
"Airbus",
"Aircraft",
"Aircraft Carrier",
"Aircraft Engine",
"Airdock",
"Airdrome",
"Airfield",
"Airfoil",
"Airframe",
"Airgun",
"Airing Cupboard",
"Airline",
"Airliner",
"Airlock",
"Airmail Letter",
"Airmailer",
"Airplane",
"Airplane Propeller",
"Airport",
"Airport Terminal",
"Airscrew",
"Airship",
"Airstrip",
"Airway",
"Aisle",
"Aladdin'S Lamp",
"Alarm",
"Alarm Clock",
"Alarm System",
"Alb",
"Album",
"Alcazar",
"Alcohol Thermometer",
"Alcohol-In-Glass Thermometer",
"Alcove",
"Alehouse",
"Alembic",
"Algometer",
"Alidad",
"Alidade",
"Allen Screw",
"Allen Wrench",
"Alley",
"Alleyway",
"Alligator Wrench",
"Almanac",
"Alms Dish",
"Alms Tray",
"Alpaca",
"Alpenstock",
"Altar",
"Altarpiece",
"Altazimuth",
"Alternator",
"Altimeter",
"Alto Relievo",
"Alto Rilievo",
"Aluminium Foil",
"Aluminum Foil",
"Amati",
"Ambulance",
"Ambulatory",
"Amen Corner",
"American Flag",
"American Organ",
"Americana",
"Ammeter",
"Ammo",
"Ammonia Clock",
"Ammunition",
"Amphibian",
"Amphibious Aircraft",
"Amphibious Vehicle",
"Amphitheater",
"Amphitheatre",
"Amphora",
"Amplifier",
"Ampulla",
"Amusement Arcade",
"Amyloid Plaque",
"Amyloid Protein Plaque",
"Anachronism",
"Anaglyph",
"Analog Clock",
"Analog Computer",
"Analog Watch",
"Analogue Computer",
"Analyser",
"Analytical Balance",
"Analyzer",
"Anamorphism",
"Anamorphosis",
"Anastigmat",
"Anastigmatic Lens",
"Anchor",
"Anchor Chain",
"Anchor Light",
"Anchor Rope",
"And Circuit",
"And Gate",
"Andiron",
"Android",
"Anechoic Chamber",
"Anemometer",
"Aneroid",
"Aneroid Barometer",
"Angiocardiogram",
"Angiogram",
"Angioscope",
"Angle Bracket",
"Angle Iron",
"Angledozer",
"Animalization",
"Ankle Brace",
"Ankle Bracelet",
"Anklet",
"Anklets",
"Ankus",
"Annals",
"Annual",
"Annulet",
"Annunciator",
"Anode",
"Answering Machine",
"Antechamber",
"Antefix",
"Antenna",
"Anteroom",
"Anthology",
"Anti-G Suit",
"Anti-Submarine Rocket",
"Antiaircraft",
"Antiaircraft Gun",
"Antiballistic Missile",
"Antifouling Paint",
"Antimacassar",
"Antiperspirant",
"Antique",
"Antiquity",
"Anvil",
"Ao Dai",
"Apadana",
"Apartment",
"Apartment Building",
"Apartment House",
"Apc",
"Aperture",
"Apiary",
"Apishamore",
"Apparatus",
"Apparel",
"Applecart",
"Appliance",
"Applicator",
"Applier",
"Applique",
"Appointment",
"Appointment Book",
"Appointment Calendar",
"Approach",
"Approach Trench",
"Apron",
"Apron String",
"Apse",
"Apsis",
"Aqua-Lung",
"Aqualung",
"Aquaplane",
"Aquarium",
"Aquatint",
"Aqueduct",
"Arabesque",
"Araroba",
"Arbor",
"Arboretum",
"Arbour",
"Arc Lamp",
"Arc Light",
"Arcade",
"Arch",
"Arch Support",
"Archeological Remains",
"Architectural Ornament",
"Architecture",
"Architrave",
"Archive",
"Archives",
"Archway",
"Arctic",
"Area",
"Areaway",
"Arena Theater",
"Argyle",
"Argyll",
"Ark",
"Arm",
"Arm Band",
"Arm Guard",
"Arm Pad",
"Armament",
"Armature",
"Armband",
"Armchair",
"Armet",
"Armhole",
"Armilla",
"Armillary Sphere",
"Armlet",
"Armoire",
"Armor",
"Armor Plate",
"Armor Plating",
"Armored Car",
"Armored Personnel Carrier",
"Armored Vehicle",
"Armory",
"Armour",
"Armour Plate",
"Armoured Car",
"Armoured Personnel Carrier",
"Armoured Vehicle",
"Armoury",
"Armrest",
"Army Base",
"Arquebus",
"Array",
"Arrester",
"Arrester Hook",
"Arrival Gate",
"Arrow",
"Arsenal",
"Art",
"Art School",
"Artefact",
"Arterial Plaque",
"Arterial Road",
"Arteriogram",
"Artery",
"Artesian Well",
"Arthrogram",
"Arthroscope",
"Article",
"Article Of Commerce",
"Articulated Ladder",
"Artifact",
"Artificial Flower",
"Artificial Heart",
"Artificial Horizon",
"Artificial Joint",
"Artificial Kidney",
"Artificial Skin",
"Artillery",
"Artillery Shell",
"Artist'S Loft",
"Ascot",
"Ash Bin",
"Ash-Bin",
"Ash-Pan",
"Ashbin",
"Ashcan",
"Ashlar",
"Ashtray",
"Aspergill",
"Aspersorium",
"Asphalt",
"Aspirator",
"Aspirin Powder",
"Assagai",
"Assault Gun",
"Assault Rifle",
"Assegai",
"Assembly",
"Assembly Hall",
"Assembly Plant",
"Astatic Coils",
"Astatic Galvanometer",
"Astrodome",
"Astrolabe",
"Astronomical Telescope",
"Astronomy Satellite",
"Athanor",
"Athenaeum",
"Atheneum",
"Athletic Facility",
"Athletic Sock",
"Athletic Supporter",
"Atlas",
"Atmometer",
"Atom Bomb",
"Atom Smasher",
"Atomic Bomb",
"Atomic Clock",
"Atomic Pile",
"Atomic Reactor",
"Atomiser",
"Atomizer",
"Atrium",
"Attache",
"Attache Case",
"Attachment",
"Attack Aircraft Carrier",
"Attack Submarine",
"Attenuator",
"Attic",
"Attic Fan",
"Attire",
"Auction Block",
"Audio Amplifier",
"Audio Cd",
"Audio Compact Disc",
"Audio System",
"Audiocassette",
"Audiogram",
"Audiometer",
"Audiotape",
"Audiovisual",
"Audiovisual Aid",
"Auditorium",
"Auger",
"Authority",
"Auto Factory",
"Autobahn",
"Autoclave",
"Autofocus",
"Autogiro",
"Autograph Album",
"Autogyro",
"Autoinjector",
"Autoloader",
"Automat",
"Automatic",
"Automatic Choke",
"Automatic Drive",
"Automatic Firearm",
"Automatic Gun",
"Automatic Pilot",
"Automatic Pistol",
"Automatic Rifle",
"Automatic Transmission",
"Automatic Weapon",
"Automation",
"Automaton",
"Automobile Engine",
"Automobile Factory",
"Automobile Horn",
"Autopilot",
"Autoradiograph",
"Autostrada",
"Auxiliary Airfield",
"Auxiliary Boiler",
"Auxiliary Engine",
"Auxiliary Pump",
"Auxiliary Research Submarine",
"Auxiliary Storage",
"Avenue",
"Aviary",
"Awl",
"Awning",
"Ax",
"Ax Head",
"Axe",
"Axe Head",
"Axis",
"Axis Of Rotation",
"Axle",
"Axle Bar",
"Axletree"

]

def generate_pair():
    # random.sample guarantees picking two UNIQUE items from the list
    item1, item2 = random.sample(items, 2)
    print("\n" + "=" * 40)
    print(f"  ITEM 1 :  {item1}")
    print(f"  ITEM 2 :  {item2}")
    print("=" * 40)
    print("-> How can you combine these into a new product?")

if __name__ == "__main__":
    print("--- MIX AND MATCH BRAINSTORMER ---")
    while True:
        generate_pair()
        user_input = input("\nPress [ENTER] for a new pair (or type 'q' to quit): ")
        if user_input.lower().strip() == 'q':
            print("Happy inventing!")
            break
